name: Build TelegramMediaExtractor EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --noconsole --icon=Telegram_Media_Unpacked.ico --name=TelegramMediaExtractor telegram_gui_extract.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TelegramMediaExtractor
        path: dist/TelegramMediaExtractor.exe
